### ISSUE TITLE
数据库

### ISSUE THREAD

**Issue by ICFlying** [chen365409389/QueueSystem#4]
有数据库初始化脚本吗？数据结构什么样的

**Comment by JackQChen** [comment]
DBBak里面添加了一个，还原下应该就好了
目前可以参考下数据及消息处理流程，硬件相关设备不同厂家区别较大，只能按实际情况来处理。

**Comment by ICFlying** [comment]
您好，谢谢，数据库可以用了，可以连接了。项目是不是需要两个数据库啊？

**Comment by ICFlying** [comment]
connectionString="Database='QueueDB';Data Source='cysoft.uicp.net';

**Comment by JackQChen** [comment]
数据库就一个，还原好以后，设置连接字符串就可以了，具体参数以实际配置为准connectionString="Database='QueueDB';Data Source='192.168.1.100';User Id='root';Password='password';charset='utf8';pooling=true"

**Comment by ICFlying** [comment]
好的谢谢，中天至祥LED通讯屏幕3.8版二次开发SDK_V130715，是2013的，ledsend.dll 库有点差异了。你那个dll能上传吗

**Comment by JackQChen** [comment]
现在led只做过视展和仰邦的，视展的链接http://www.ledvs.com/down/html/?20.html
仰邦的http://www.onbonbx.com/download/160.html
如果硬件不一样，肯定还是要单独处理的

**Comment by ICFlying** [comment]
谢谢回复，原来有用过扬邦的，现在编译测试没问题。













13829678006


13829678006@139.com


13829678006







电子名片新出VIP模板啦，快来体验>>




扫一扫,


快速添加名片到手机




--------------------------------------------------------------------------------





------------------ 原始邮件 ------------------




 
 发件人: JackChen  <notifications@github.com>
 

 
 发送时间: 2018-12-21 20:17:33
 

 
 收件人:chen365409389/QueueSystem <queuesystem@noreply.github.com> 

 
 抄送:本人 <13829678006@139.com>,Author <author@noreply.github.com> 

 
 主题: Re: [chen365409389/QueueSystem] 数据库 (#4)
 



现在led只做过视展和仰邦的，视展的链接http://www.ledvs.com/down/html/?20.html
 仰邦的http://www.onbonbx.com/download/160.html
 如果硬件不一样，肯定还是要单独处理的
