### ISSUE TITLE
WeChatService

### ISSUE THREAD

**Issue by ICFlying** [chen365409389/QueueSystem#5]
大牛，微信服务可以用吗？我测试总出错，不知是姿势不对还是啥问题。

**Comment by ICFlying** [comment]
不好意思，找到了，配置文件没有添加AccessKey，

**Comment by JackQChen** [comment]
嗯，微信服务这个还需要第三方接入才有效果，没有的话只能测试作为参考。

**Comment by ICFlying** [comment]
您好，有个项目找您下，方便不？发自我的华为手机-------- 原始邮件 --------主题：Re: [chen365409389/QueueSystem] WeChatService (#5)发件人：JackChen 收件人：chen365409389/QueueSystem 抄送：ICFlying <13829678006@139.COM>,Author 嗯，微信服务这个还需要第三方接入才有效果，没有的话只能测试作为参考。



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/chen365409389/QueueSystem","title":"chen365409389/QueueSystem","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/chen365409389/QueueSystem"}},"updates":{"snippets":[{"icon":"PERSON","message":"@chen365409389 in #5: 嗯，微信服务这个还需要第三方接入才有效果，没有的话只能测试作为参考。"}],"action":{"name":"View Issue","url":"https://github.com/chen365409389/QueueSystem/issues/5#issuecomment-463445053"}}}

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/chen365409389/QueueSystem/issues/5#issuecomment-463445053",

"url": "https://github.com/chen365409389/QueueSystem/issues/5#issuecomment-463445053",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by JackQChen** [comment]
你直接联系我就行，电话/微信：15002902506，QQ：121955443
