### ISSUE TITLE
授权文件在哪里？

### ISSUE THREAD

**Issue by dengjiede** [chen365409389/QueueSystem#7]
消息服务管理程序的授权文件在哪里？

**Comment by JackQChen** [comment]
QueueSystem/MessageService/MessageServer/FrmMain.cs
29~58行是服务的授权控制，注释掉以后重新编译就不验证授权了，或者从SoftwareLicense项目的Generator生成一个License文件放在程序目录就可以了

**Comment by dengjiede** [comment]
再请问一下这个系统有没有安装部署文档？我把所有的程序都生成了一遍，授权也弄了，服务管理器也启动了，但是几个客户端还是启动不起呢？

**Comment by JackQChen** [comment]
客户端报错还是缺少配置还是？可以加我QQ121955443

**Comment by dengjiede** [comment]
大神，我已经加你了 梦在兴中   1544857622  你同意下
