### ISSUE TITLE
Documentation on Setting up the project.

### ISSUE THREAD

**Issue by jassimkm** [chen365409389/QueueSystem#9]
Hello,
Do you have any documentation available for setting up the project? 
Some dll files are missing or outdated . 
Would appreciate if you can provide those .

**Comment by JackQChen** [comment]
Hi jassimkm, since this project is customized and implemented on-site, there is no installation documentation available. The relevant libraries can be found [here](https://github.com/JackQChen/QueueSystem/tree/master/Lib).
